### ISSUE TITLE
CoAP assembly appears to have lost its strong name

### ISSUE THREAD

**Issue by lorenh** [Com-AugustCellars/CoAP-CSharp#34]
I see this now when I look at the assembly metadata, was this intentional?
   CoAP, Version=1.1.6.0, Culture=neutral, PublicKeyToken=null

It used to be something like this:
    CoAP, Version=1.1.6.0, Culture=neutral, PublicKeyToken=e2c10a743037308b, processorArchitecture=MSIL

It doesn't seem to be causing me any issues once I manually added back the reference, but I am just checking to see if this was on purpose or not.  There was some weird stuff happening when I tried to upgrade the NuGet package that might have been related, but I manually played with the packages and references and got things to compile.  It could have been something I did out of sequence or something.  Just wanted to check.

**Comment by jimsch** [comment]
Should be fixed in 1.1.8.1
