### ISSUE TITLE
Equivalent of "coap-client -u"

### ISSUE THREAD

**Issue by Moskus** [Com-AugustCellars/CoAP-CSharp#41]
IKEA just made some changes to their API, and I can't for the life of me figure out the .NET way to do the same as specified here: https://twitter.com/home_assistant/status/925373865802502144

Earlier I haven't had the need to specify the "-u" parameter (like -u "Client_identity"), but now I first have to specify it to get access (apparently). This is not enough (and I apologize for the VB code):

        `
        Dim authKey As OneKey = New OneKey()
        authKey.Add(COSE.CoseKeyKeys.KeyType, COSE.GeneralValues.KeyType_Octet)
        authKey.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(System.Text.Encoding.UTF8.GetBytes(Me.Key)))
        'authKey.Add(COSE.CoseKeyKeys.KeyIdentifier, CBORObject.FromObject(System.Text.Encoding.UTF8.GetBytes("Client_identity")))

        Dim pskEndpoint As CoAP.Net.CoAPEndPoint = New DTLSClientEndPoint(authKey)
        pskEndpoint.Start()

        Dim request As Request = Request.NewPut()

        request.URI = New Uri("coaps://" & IPaddress & "/15011/9063/")
        request.EndPoint = pskEndpoint
        request.AckTimeout = 5000
        request.SetPayload("{""9090"":""MyApp""}")

        request.Send()

        Dim response As Response = request.WaitForResponse(5000)
`

Withouth the last "authKey.Add" the request fails to get authenticated. With it I get "method not allowed".

**Comment by jimsch** [comment]
The text says to use PUT not POST in the first message.  So that is probably the reason for the method not allowed error response.  There is a difference between those two methods.

You are setting the key identity correctly with the last authKey.Add although from the picture I cannot tell if that is an upper or lower case 'i'.  Based on the error, it would appear that it is a lower case 'i'.

**Comment by Moskus** [comment]
I thought I was using PUT:
'Dim request As Request = Request.NewPut()'

**Comment by jimsch** [comment]
I wrote backward  should be POST not PUT

**Comment by Moskus** [comment]
Yes. That helped! Solved!

**Comment by Hydro8** [comment]
How do you discover every devices after authentication ?

**Comment by bmachuletz** [comment]
Hi,

 

this is the constructor of my Tradfi-class. As I said before the code is currently working on the latest gateway version and I am doing no special authentication things. When my other code will be ready tob e published I would upload my project to github. It is a, I would say „broker“ for Tradfri and homegear (an maybe I will try some sonoff stuff in the future). Hope this would help you a bit.

 

        public TradfriClient()
        {
            try
            {
                userKey = new OneKey();

                DeviceList = new List<TradfriDevice>();

                userKey.Add(CoseKeyKeys.KeyType, GeneralValues.KeyType_Octet);
                userKey.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(Encoding.UTF8.GetBytes("XRgp1htdDiVkBQCV")));
                           client = new CoapClient(new Uri("coaps://HOSTNAME_OF_TRADGRI_GATEWAY"))
                {
                    EndPoint = ep
                };
                  
                ep.Start();


                IEnumerable<WebLink> resources = client.Discover();
                foreach (var resource in resources)
                {
                    foreach (string s in HomeMagic.Shared.StringHelper.GetMatches(resource.ToString(), "<", ">"))
                    {
                        client.UriPath = s;
                        Response response = client.Get();

                        Console.WriteLine(response.PayloadString);

                        try
                        {
                            TradfriDevice dev = Newtonsoft.Json.JsonConvert.DeserializeObject<TradfriDevice>(response.PayloadString);
                            if (dev != null)
                            {
                                if (dev.Id >= 65537
                                    && dev.TradfriDeviceName != "TRADFRI group" && dev.TradfriDeviceName != "RELAX"
                                    && dev.TradfriDeviceName != "FOCUS" && dev.TradfriDeviceName != "EVERYDAY")
                                {
                                    dev.Path = s;
                                    DeviceList.Add(dev);
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex.Message.ToString());
                            // nothing
                        }
            
                    }
                }
                // ep.Stop();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message.ToString());
            }
        } 

 

 

 

Von: Hydro8 [mailto:notifications@github.com] 
Gesendet: Freitag, 24. November 2017 22:46
An: Com-AugustCellars/CoAP-CSharp <CoAP-CSharp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Com-AugustCellars/CoAP-CSharp] Equivalent of "coap-client -u" (#41)

 

How do you discover every devices after authentication ?

**Comment by Hydro8** [comment]
ep.start(); return an error : System.NullReferenceException

**Comment by Hydro8** [comment]
Ok I manage to get this code work by adding ep = new DTLSClientEndPoint(userKey);

**Comment by Hydro8** [comment]
So with 

`userKey = new OneKey();
            
            userKey.Add(CoseKeyKeys.KeyType, GeneralValues.KeyType_Octet);
            userKey.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(Encoding.UTF8.GetBytes(PackageHost.GetSettingValue<string>("GatewayKey"))));
            userKey.Add(CoseKeyKeys.KeyIdentifier, CBORObject.FromObject(System.Text.Encoding.UTF8.GetBytes("Constellation")));
            ep = new DTLSClientEndPoint(userKey,9999);
            client = new CoapClient(new Uri($"coaps://" + PackageHost.GetSettingValue<string>("GatewayIP")))
            {
                EndPoint = ep
            };
            ep.Start();
            IEnumerable<WebLink> items = client.Discover();`

it works, I can see devices but discover option doesn't.

I tried 

`if (node.Attributes.Observable)
                        {
                            CoapObserveRelation relation1 = client.Observe(r => { EventIn(node.Uri, r); });
                        }`

But no event when I change my bulb color / dimmer level.

Any idea where the problem come from ?

**Comment by bmachuletz** [comment]
I haven’t tried this so far. But if you get it to work, i would be very interested in that piece of code. At this time I am periodically polling the state oft he bulbs…

 

Sorry..

 

Von: Hydro8 [mailto:notifications@github.com] 
Gesendet: Samstag, 25. November 2017 12:12
An: Com-AugustCellars/CoAP-CSharp <CoAP-CSharp@noreply.github.com>
Cc: bmachuletz <bmachuletz@mnetworx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [Com-AugustCellars/CoAP-CSharp] Equivalent of "coap-client -u" (#41)

 

So with

`userKey = new OneKey();

        userKey.Add(CoseKeyKeys.KeyType, GeneralValues.KeyType_Octet);
        userKey.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(Encoding.UTF8.GetBytes(PackageHost.GetSettingValue<string>("GatewayKey"))));
        userKey.Add(CoseKeyKeys.KeyIdentifier, CBORObject.FromObject(System.Text.Encoding.UTF8.GetBytes("Constellation")));
        ep = new DTLSClientEndPoint(userKey,9999);
        client = new CoapClient(new Uri($"coaps://" + PackageHost.GetSettingValue<string>("GatewayIP")))
        {
            EndPoint = ep
        };
        ep.Start();
        IEnumerable<WebLink> items = client.Discover();`

it works, I can see devices but discover option doesn't.

I tried

if (node.Attributes.Observable) { CoapObserveRelation relation1 = client.Observe(r => { EventIn(node.Uri, r); }); }

But no event when I change my bulb color / dimmer level.

Any idea where the problem come from ?

**Comment by Hydro8** [comment]
Any update on this?
