### ISSUE TITLE
Com.Augustcellars.Coap and Xamarin.Mac

### ISSUE THREAD

**Issue by StefanRademakers** [Com-AugustCellars/CoAP-CSharp#45]
Hello there, I'm trying to use the Com.Augustcellars.Coap package from nuget in a Xamarin.Mac Modern project (Visual Studio for mac).
But when I import the latest version 1.1.8.1 the Namespace Com.Augustcellars.Coap is unknown. If I import an older version e.a. 1.1.6
if does seem to work but I get a System.Net.Sockets.SocketException (mono-io-layer-error (100001)).
Do you have any ideas on this? Should it be possible to get it to work? Seems to work in a .netStandard 2.0 project.

**Comment by jimsch** [comment]
One of the things that was fixed when moving up to the 1.1.8 versions was that socket exception layer.  Off the top of my head I don't have any ideas and wont be able to look at it for a week.

**Comment by jimsch** [comment]
Sleeping on this. what runtime version are you targeting w/ Xamarin.Mac?  Can you get a choice?  You need to be running 4.6.2 of the .NET Framework in order to allow for the use of a .netStandard 1.0 component.  One of the components that I rely on switched to .netStarted 1.x and thus I switched as well.

**Comment by StefanRademakers** [comment]
Hello Jimsch, thanks for the fast reply. The project uses 'Xamarin.Mac Modern', but I have libraries working that use .Net Standard 2.0. So it's unclear to me why it does't work. I'll investigate further!
Thanks

**Comment by jimsch** [comment]
Latest drop up today has Netstandard 1.3 and 2.0 versions.
