### ISSUE TITLE
Context Object

### ISSUE THREAD

**Issue by davidwallis3101** [Com-AugustCellars/CoAP-CSharp#50]
Hi,

I am looking at your observe example but not sure what object I should be using as a contextObject - it doesnt seem clear from the example.. but that might be me being thick!

Thanks

David

**Comment by jimsch** [comment]
The contextObject is an object of your choice that holds information about the specific notification you are looking for.  This allows for a function on your object to be called when a notification happens.

**Comment by davidwallis3101** [comment]
Doh! Erm.. It is me being thick!
