### ISSUE TITLE
.Net standard 2.0 support

### ISSUE THREAD

**Issue by toomasz** [Com-AugustCellars/CoAP-CSharp#52]
Hi, are you considering migrating this coap library to netstandard?
That would make it possible to reference it from .net core.

I can actually work on that :)

**Comment by jimsch** [comment]
.net standard 1.0 is on my list of things that need to be done.  I hope to get there in the next couple of months but I need to get all of my other code working correctly as well :(

**Comment by jimsch** [comment]
NetStandard 1.3 and 2.0 are part of the 1.2 drop that just went up.
