### ISSUE TITLE
Recall that Encoding.UTF8 adds byte-order marks

### ISSUE THREAD

**Issue by peteroupc** [Com-AugustCellars/CoAP-CSharp#55]
This is to remind you that [`Encoding.UTF8`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.utf8) encodes text strings by beginning them with byte-order marks.  Thus, code like the following may not work as expected:

     CBORObject.FromObject(Encoding.UTF8.GetBytes("TEXT"))

My library contains a `DataUtilities.GetUtf8Bytes` method that can be used instead:

     CBORObject.FromObject(DataUtilities.GetUtf8Bytes("TEXT", false))

**Comment by jimsch** [comment]
That is annoying - and I have never actually seen it emit the preamble in practice.   The entire idea of emitting a BOM for a UTF8 encoding annoys me to no end.  Its not like it is a useful marker.

**Comment by peteroupc** [comment]
Closing this issue as moot.  As explained in the same documentation, `Encoding.UTF8`'s methods does not add a byte-order mark automatically; it merely _provides_ a byte-order mark with the `GetPreamble` method.
